In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [6]:
np.array([1,2,3,4,"sudh",3+5j])

array(['1', '2', '3', '4', 'sudh', '(3+5j)'], dtype='<U64')

In [8]:
np.array([1,2,3,4.0,6.0])

array([1., 2., 3., 4., 6.])

In [11]:
np.array([[1,2],[3,4],[3,6]])

array([[1, 2],
       [3, 4],
       [3, 6]])

In [12]:
np.array([1,2,3],ndmin=30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [13]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.array([(3,4),(4,5)])

array([[3, 4],
       [4, 5]])

In [16]:
arr = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])

In [17]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [18]:
type(arr[0][0])

numpy.int32

In [19]:
type(arr[0][1])

numpy.int64

In [20]:
arr  = np.array([[1,3],[3,4]])

In [21]:
arr

array([[1, 3],
       [3, 4]])

In [22]:
arr[0][1]

3

In [24]:
type(arr[1][1])

numpy.int32

In [25]:
np.mat(arr)

matrix([[1, 3],
        [3, 4]])

In [26]:
l=[1,2,3,4,5,6]

In [28]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [29]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [32]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [36]:
np.asarray(mat)

NameError: name 'mat' is not defined

In [35]:
np.asanyarray(mat)

NameError: name 'mat' is not defined

In [37]:
issubclass(np.ndarray,np.matrix )

False

In [38]:
arr

array([[1, 3],
       [3, 4]])

In [39]:
a=arr

In [40]:
b=np.copy(arr)

In [41]:
arr[0][0]=67

In [42]:
arr

array([[67,  3],
       [ 3,  4]])

In [43]:
b

array([[1, 3],
       [3, 4]])

In [44]:
arr[0:10]

array([[67,  3],
       [ 3,  4]])

In [45]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [46]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [47]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [50]:
np.fromfunction(lambda i , j :i**j,(4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [51]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [53]:
np.fromfunction(lambda i , j :i/j,(3,3))

C:\Users\amit\AppData\Local\Temp/ipykernel_13776/2281161872.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))
C:\Users\amit\AppData\Local\Temp/ipykernel_13776/2281161872.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [55]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [56]:
(i*i for i in range(5))

<generator object <genexpr> at 0x000001FBF97E56D0>

In [60]:
def test(x):
    yield x

In [61]:
test(5)

<generator object test at 0x000001FBF97E5C10>

In [63]:
gen
for i in gen :
    print(i)

NameError: name 'gen' is not defined

In [64]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [65]:
np.fromstring("1,2,3,4,5",sep=", ",dtype=int)

array([1, 2, 3, 4, 5])

In [66]:
np.fromstring("123 21423 324 3245 65",sep=' ',dtype=complex)

array([  123.+0.j, 21423.+0.j,   324.+0.j,  3245.+0.j,    65.+0.j])

In [67]:
l=[1,2,3,4,5,6]

In [68]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [69]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])

In [70]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [72]:
type(arr1)

numpy.ndarray

In [73]:
arr1.ndim

2

In [74]:
arr1.size

12

In [75]:
arr1.shape

(3, 4)

In [76]:
arr1.dtype

dtype('int32')

In [77]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [78]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [79]:
arr2.size

16

In [80]:
arr2.shape

(2, 2, 4)

In [81]:
arr2.ndim

3

In [82]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [83]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [84]:
arr4.shape

(1, 4, 2, 4)

In [85]:
arr4.ndim

4

In [86]:
range(5)

range(0, 5)

In [87]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [90]:
list(range(6.6,9,.3))

TypeError: 'float' object cannot be interpreted as an integer

In [92]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [91]:
np.arange(6.6,9,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [93]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [97]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [98]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [99]:
np.linspace(.3,.5,5)

array([0.3 , 0.35, 0.4 , 0.45, 0.5 ])

In [100]:
np.linspace(.1,.11,5)

array([0.1   , 0.1025, 0.105 , 0.1075, 0.11  ])

In [101]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [102]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [103]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [104]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [106]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [107]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [108]:
np.ones((2,4,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [110]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [112]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [113]:
np.empty((3,4))

array([[0.        , 0.        , 0.        , 1.        ],
       [0.5       , 0.33333333, 2.        , 1.        ],
       [0.66666667, 3.        , 1.5       , 1.        ]])

In [114]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [121]:
np.linspace([1,6],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [122]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [123]:
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [124]:
np.logspace([2],[3],axis=1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [125]:
d=np.linspace(4,7,40)

In [126]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [127]:
d.ndim

1

In [128]:
d.shape

(40,)

In [129]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [131]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [132]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [134]:
np.random.rand(3)

array([0.80074815, 0.11696089, 0.09734056])

In [135]:
np.random.randn(5)

array([-1.25126124, -0.13148718, -0.64151092, -0.66230262, -0.94711897])

In [138]:
np.random.randn(2,2,3)

array([[[-1.44290382,  0.32079609, -0.17868079],
        [ 0.89405378, -1.0484765 ,  0.18147533]],

       [[ 0.53819003,  1.06350181,  0.14143337],
        [ 1.82256652,  0.09860712,  0.60353248]]])

In [141]:
np.random.randint(5,50,(4,4))

array([[17, 16, 26, 30],
       [49, 42,  8,  7],
       [22, 16, 12, 39],
       [19, 26,  6, 25]])

In [142]:
arr=np.random.randint(3,9,(3,3))

In [143]:
arr

array([[5, 4, 3],
       [6, 3, 6],
       [5, 7, 3]])

In [144]:
arr.reshape(1,9)

array([[5, 4, 3, 6, 3, 6, 5, 7, 3]])

In [145]:
arr.reshape(9,1)

array([[5],
       [4],
       [3],
       [6],
       [3],
       [6],
       [5],
       [7],
       [3]])

In [146]:
arr.reshape(1,1,9)

array([[[5, 4, 3, 6, 3, 6, 5, 7, 3]]])

In [147]:
arr.reshape(3,3,1)

array([[[5],
        [4],
        [3]],

       [[6],
        [3],
        [6]],

       [[5],
        [7],
        [3]]])

In [148]:
arr.reshape(1,9)

array([[5, 4, 3],
       [6, 3, 6],
       [5, 7, 3]])

In [149]:
arr.reshape(1,-873295635)

array([[5, 4, 3, 6, 3, 6, 5, 7, 3]])

In [154]:
arr

array([[5, 4, 3],
       [6, 3, 6],
       [5, 7, 3]])

In [155]:
arr.max()

7

In [156]:
arr.min()

3

In [157]:
arr = np.random.randint(4,100, (5,5))

In [158]:
arr

array([[91, 38, 60, 96, 32],
       [34, 30, 72,  4, 91],
       [61, 25, 71, 27, 77],
       [ 4, 51, 55, 30, 18],
       [11, 60, 53, 78, 82]])

In [159]:
arr[3:,3:]

array([[30, 18],
       [78, 82]])

In [160]:
arr[:,[1,3]]

array([[38, 96],
       [30,  4],
       [25, 27],
       [51, 30],
       [60, 78]])

In [161]:
arr

array([[91, 38, 60, 96, 32],
       [34, 30, 72,  4, 91],
       [61, 25, 71, 27, 77],
       [ 4, 51, 55, 30, 18],
       [11, 60, 53, 78, 82]])

In [162]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [163]:
arr[arr>10]

array([91, 38, 60, 96, 32, 34, 30, 72, 91, 61, 25, 71, 27, 77, 51, 55, 30,
       18, 11, 60, 53, 78, 82])

In [164]:
arr*arr

array([[8281, 1444, 3600, 9216, 1024],
       [1156,  900, 5184,   16, 8281],
       [3721,  625, 5041,  729, 5929],
       [  16, 2601, 3025,  900,  324],
       [ 121, 3600, 2809, 6084, 6724]])

In [167]:
arr1 = np.random.randint(2,3,(3,2))

In [168]:
arr1

array([[2, 2],
       [2, 2],
       [2, 2]])

In [169]:
arr1 = np.random.randint(2,4,(3,3))

In [170]:
arr2 = np.random.randint(2,4,(3,3))

In [171]:
arr1

array([[2, 3, 3],
       [2, 2, 2],
       [3, 2, 2]])

In [172]:
arr2

array([[3, 2, 2],
       [3, 3, 3],
       [2, 3, 3]])

In [173]:
arr1*arr2

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [174]:
arr1@arr2

array([[21, 22, 22],
       [16, 16, 16],
       [19, 18, 18]])

In [175]:
arr**2

array([[8281, 1444, 3600, 9216, 1024],
       [1156,  900, 5184,   16, 8281],
       [3721,  625, 5041,  729, 5929],
       [  16, 2601, 3025,  900,  324],
       [ 121, 3600, 2809, 6084, 6724]], dtype=int32)

In [176]:
arr/0

C:\Users\amit\AppData\Local\Temp/ipykernel_13776/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [177]:
arr**2

array([[8281, 1444, 3600, 9216, 1024],
       [1156,  900, 5184,   16, 8281],
       [3721,  625, 5041,  729, 5929],
       [  16, 2601, 3025,  900,  324],
       [ 121, 3600, 2809, 6084, 6724]], dtype=int32)

In [178]:
arr = np.zeros((3,4))

In [179]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [180]:
a = np.array([1,2,3,5])

In [181]:
a

array([1, 2, 3, 5])

In [182]:
arr +a

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [183]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [184]:
b = np.array([5,6,7])

In [185]:
b

array([5, 6, 7])

In [186]:
b.reshape(3,1) +arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [187]:
b

array([5, 6, 7])

In [188]:
b.T

array([5, 6, 7])

In [189]:
b = np.array([[5,6,7]])

In [190]:
b.T +arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [191]:
arr = np.random.rand(5,4)

In [192]:
arr

array([[0.96563851, 0.06688928, 0.19680859, 0.15869969],
       [0.91604326, 0.46208748, 0.58569208, 0.62240813],
       [0.25501891, 0.81335108, 0.87132032, 0.31136971],
       [0.35347054, 0.93644804, 0.25277049, 0.50505268],
       [0.49791329, 0.41210784, 0.08528472, 0.79805842]])

In [193]:
np.sqrt(arr)

array([[0.98266907, 0.25862962, 0.44363114, 0.3983713 ],
       [0.95710149, 0.67977017, 0.76530522, 0.78892847],
       [0.50499397, 0.90185979, 0.9334454 , 0.55800512],
       [0.59453389, 0.96770246, 0.50276286, 0.71067058],
       [0.70562971, 0.64195626, 0.29203547, 0.89334116]])

In [194]:
np.exp(arr)

array([[2.62646414, 1.06917709, 1.21751097, 1.17198593],
       [2.49938139, 1.58738416, 1.79623369, 1.86340998],
       [1.29048602, 2.25545355, 2.39006443, 1.36529389],
       [1.42400104, 2.55090461, 1.28758773, 1.65707281],
       [1.64528445, 1.50999726, 1.08902709, 2.22122406]])

In [195]:
np.log10(arr)

array([[-0.01518542, -1.17464348, -0.70595595, -0.79942392],
       [-0.03808402, -0.3352758 , -0.23233065, -0.20592474],
       [-0.59342761, -0.08972195, -0.05982216, -0.50672364],
       [-0.45164677, -0.02851631, -0.59727362, -0.29666332],
       [-0.30284628, -0.38498913, -1.06912878, -0.09796532]])

In [196]:
arr1 = np.random.randint(2,5,(5,5))

In [197]:
np.log10(arr1)

array([[0.60205999, 0.30103   , 0.60205999, 0.47712125, 0.47712125],
       [0.47712125, 0.30103   , 0.47712125, 0.47712125, 0.60205999],
       [0.30103   , 0.60205999, 0.47712125, 0.47712125, 0.47712125],
       [0.47712125, 0.60205999, 0.47712125, 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.30103   , 0.60205999, 0.30103   ]])

In [198]:
arr1

array([[4, 2, 4, 3, 3],
       [3, 2, 3, 3, 4],
       [2, 4, 3, 3, 3],
       [3, 4, 3, 2, 2],
       [3, 3, 2, 4, 2]])

In [199]:
np.seed

AttributeError: module 'numpy' has no attribute 'seed'

In [200]:
np.random.seed(13)

In [204]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])